title: Grace Qi Luan
logo: GL_headshot.png
description: "Data Scientist with dual master’s degrees in Applied Data Science and Communication, combining technical expertise and storytelling to deliver actionable insights for diverse stakeholders. With over 10 years of experience in marketing and business consulting, I specialize in data-informed decision-making and strategic consultation across digital marketing, healthcare, and insurance industries. Proficient in Python, R, SQL, Power BI, GitHub, Google Looker Studio, Google Analytics, and digital advertising platforms, I am passionate about using data to drive innovation and empower organizations."
#show_downloads: true
theme: jekyll-theme-minimal
