title: Grace Qi Luan
logo: GL_headshot.png
description: 'Data Scientist with dual master’s degrees in Applied Data Science and Communication, blending technical expertise with storytelling to transform complex data into actionable insights.'
description:'With over 10 years of marketing and business consulting experience in healthcare and insurance industries, I excel in data-informed decision-making and strategic consultation, driven by a passion for expanding into new industries and tackling diverse challenges. '
description: 'Proficient in Python, R, SQL, Power BI, Google Looker Studio, Google Analytics, and digital advertising platforms, I bring a results-oriented approach to leveraging data to empower organizations and drive measurable success.'
#show_downloads: true
theme: jekyll-theme-minimal
